name = "Survroso"
uuid = "6cedf0bc-ba85-4112-b302-eaf18ec0c981"
authors = ["feronromane <148044017+feronromane@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
DataFrames = "1.7.0"
KernelDensity = "0.6.9"
Plots = "1.40.9"
StatsPlots = "0.15.7"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
