name = "Survroso"
uuid = "6cedf0bc-ba85-4112-b302-eaf18ec0c981"
authors = ["feronromane <148044017+feronromane@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
